"""
forms used for site
"""

from flask_wtf import Form
from wtforms import StringField, SelectField, validators

class realm_form(Form):
    realm_select  = SelectField('Select Realm', choices=[
         ("Aegwynn (US)" , "Aegwynn (US)"),
         ("Aerie Peak (US)" , "Aerie Peak (US)"),
         ("Agamaggan (US)" , "Agamaggan (US)"),
         ("Aggramar (US)" , "Aggramar (US)"),
         ("Akama (US)" , "Akama (US)"),
         ("Alexstrasza (US)" , "Alexstrasza (US)"),
         ("Alleria (US)" , "Alleria (US)"),
         ("Altar of Storms (US)" , "Altar of Storms (US)"),
         ("Alterac Mountains (US)" , "Alterac Mountains (US)"),
         ("Aman'Thul (US)" , "Aman'Thul (US)"),
         ("Andorhal (US)" , "Andorhal (US)"),
         ("Anetheron (US)" , "Anetheron (US)"),
         ("Antonidas (US)" , "Antonidas (US)"),
         ("Anub'arak (US)" , "Anub'arak (US)"),
         ("Anvilmar (US)" , "Anvilmar (US)"),
         ("Arathor (US)" , "Arathor (US)"),
         ("Archimonde (US)" , "Archimonde (US)"),
         ("Area 52 (US)" , "Area 52 (US)"),
         ("Argent Dawn (US)" , "Argent Dawn (US)"),
         ("Arthas (US)" , "Arthas (US)"),
         ("Arygos (US)" , "Arygos (US)"),
         ("Auchindoun (US)" , "Auchindoun (US)"),
         ("Azgalor (US)" , "Azgalor (US)"),
         ("Azjol-Nerub (US)" , "Azjol-Nerub (US)"),
         ("Azralon (US)" , "Azralon (US)"),
         ("Azshara (US)" , "Azshara (US)"),
         ("Azuremyst (US)" , "Azuremyst (US)"),
         ("Baelgun (US)" , "Baelgun (US)"),
         ("Balnazzar (US)" , "Balnazzar (US)"),
         ("Barthilas (US)" , "Barthilas (US)"),
         ("Black Dragonflight (US)" , "Black Dragonflight (US)"),
         ("Blackhand (US)" , "Blackhand (US)"),
         ("Blackrock (US)" , "Blackrock (US)"),
         ("Blackwater Raiders (US)" , "Blackwater Raiders (US)"),
         ("Blackwing Lair (US)" , "Blackwing Lair (US)"),
         ("Blade's Edge (US)" , "Blade's Edge (US)"),
         ("Bladefist (US)" , "Bladefist (US)"),
         ("Bleeding Hollow (US)" , "Bleeding Hollow (US)"),
         ("Blood Furnace (US)" , "Blood Furnace (US)"),
         ("Bloodhoof (US)" , "Bloodhoof (US)"),
         ("Bloodscalp (US)" , "Bloodscalp (US)"),
         ("Bonechewer (US)" , "Bonechewer (US)"),
         ("Borean Tundra (US)" , "Borean Tundra (US)"),
         ("Boulderfist (US)" , "Boulderfist (US)"),
         ("Bronzebeard (US)" , "Bronzebeard (US)"),
         ("Burning Blade (US)" , "Burning Blade (US)"),
         ("Burning Legion (US)" , "Burning Legion (US)"),
         ("Caelestrasz (US)" , "Caelestrasz (US)"),
         ("Cairne (US)" , "Cairne (US)"),
         ("Cenarion Circle (US)" , "Cenarion Circle (US)"),
         ("Cenarius (US)" , "Cenarius (US)"),
         ("Cho'gall (US)" , "Cho'gall (US)"),
         ("Chromaggus (US)" , "Chromaggus (US)"),
         ("Coilfang (US)" , "Coilfang (US)"),
         ("Crushridge (US)" , "Crushridge (US)"),
         ("Daggerspine (US)" , "Daggerspine (US)"),
         ("Dalaran (US)" , "Dalaran (US)"),
         ("Dalvengyr (US)" , "Dalvengyr (US)"),
         ("Dark Iron (US)" , "Dark Iron (US)"),
         ("Darkspear (US)" , "Darkspear (US)"),
         ("Darrowmere (US)" , "Darrowmere (US)"),
         ("Dath'Remar (US)" , "Dath'Remar (US)"),
         ("Dawnbringer (US)" , "Dawnbringer (US)"),
         ("Deathwing (US)" , "Deathwing (US)"),
         ("Demon Soul (US)" , "Demon Soul (US)"),
         ("Dentarg (US)" , "Dentarg (US)"),
         ("Destromath (US)" , "Destromath (US)"),
         ("Dethecus (US)" , "Dethecus (US)"),
         ("Detheroc (US)" , "Detheroc (US)"),
         ("Doomhammer (US)" , "Doomhammer (US)"),
         ("Draenor (US)" , "Draenor (US)"),
         ("Dragonblight (US)" , "Dragonblight (US)"),
         ("Dragonmaw (US)" , "Dragonmaw (US)"),
         ("Drak'Tharon (US)" , "Drak'Tharon (US)"),
         ("Drak'thul (US)" , "Drak'thul (US)"),
         ("Draka (US)" , "Draka (US)"),
         ("Drakkari (US)" , "Drakkari (US)"),
         ("Dreadmaul (US)" , "Dreadmaul (US)"),
         ("Drenden (US)" , "Drenden (US)"),
         ("Dunemaul (US)" , "Dunemaul (US)"),
         ("Durotan (US)" , "Durotan (US)"),
         ("Duskwood (US)" , "Duskwood (US)"),
         ("Earthen Ring (US)" , "Earthen Ring (US)"),
         ("Echo Isles (US)" , "Echo Isles (US)"),
         ("Eitrigg (US)" , "Eitrigg (US)"),
         ("Eldre'Thalas (US)" , "Eldre'Thalas (US)"),
         ("Elune (US)" , "Elune (US)"),
         ("Emerald Dream (US)" , "Emerald Dream (US)"),
         ("Eonar (US)" , "Eonar (US)"),
         ("Eredar (US)" , "Eredar (US)"),
         ("Executus (US)" , "Executus (US)"),
         ("Exodar (US)" , "Exodar (US)"),
         ("Farstriders (US)" , "Farstriders (US)"),
         ("Feathermoon (US)" , "Feathermoon (US)"),
         ("Fenris (US)" , "Fenris (US)"),
         ("Firetree (US)" , "Firetree (US)"),
         ("Fizzcrank (US)" , "Fizzcrank (US)"),
         ("Frostmane (US)" , "Frostmane (US)"),
         ("Frostmourne (US)" , "Frostmourne (US)"),
         ("Frostwolf (US)" , "Frostwolf (US)"),
         ("Galakrond (US)" , "Galakrond (US)"),
         ("Gallywix (US)" , "Gallywix (US)"),
         ("Garithos (US)" , "Garithos (US)"),
         ("Garona (US)" , "Garona (US)"),
         ("Garrosh (US)" , "Garrosh (US)"),
         ("Ghostlands (US)" , "Ghostlands (US)"),
         ("Gilneas (US)" , "Gilneas (US)"),
         ("Gnomeregan (US)" , "Gnomeregan (US)"),
         ("Goldrinn (US)" , "Goldrinn (US)"),
         ("Gorefiend (US)" , "Gorefiend (US)"),
         ("Gorgonnash (US)" , "Gorgonnash (US)"),
         ("Greymane (US)" , "Greymane (US)"),
         ("Grizzly Hills (US)" , "Grizzly Hills (US)"),
         ("Gul'dan (US)" , "Gul'dan (US)"),
         ("Gundrak (US)" , "Gundrak (US)"),
         ("Gurubashi (US)" , "Gurubashi (US)"),
         ("Hakkar (US)" , "Hakkar (US)"),
         ("Haomarush (US)" , "Haomarush (US)"),
         ("Hellscream (US)" , "Hellscream (US)"),
         ("Hydraxis (US)" , "Hydraxis (US)"),
         ("Hyjal (US)" , "Hyjal (US)"),
         ("Icecrown (US)" , "Icecrown (US)"),
         ("Illidan (US)" , "Illidan (US)"),
         ("Jaedenar (US)" , "Jaedenar (US)"),
         ("Jubei'Thos (US)" , "Jubei'Thos (US)"),
         ("Kael'thas (US)" , "Kael'thas (US)"),
         ("Kalecgos (US)" , "Kalecgos (US)"),
         ("Kargath (US)" , "Kargath (US)"),
         ("Kel'Thuzad (US)" , "Kel'Thuzad (US)"),
         ("Khadgar (US)" , "Khadgar (US)"),
         ("Khaz Modan (US)" , "Khaz Modan (US)"),
         ("Khaz'goroth (US)" , "Khaz'goroth (US)"),
         ("Kil'jaeden (US)" , "Kil'jaeden (US)"),
         ("Kilrogg (US)" , "Kilrogg (US)"),
         ("Kirin Tor (US)" , "Kirin Tor (US)"),
         ("Korgath (US)" , "Korgath (US)"),
         ("Korialstrasz (US)" , "Korialstrasz (US)"),
         ("Kul Tiras (US)" , "Kul Tiras (US)"),
         ("Laughing Skull (US)" , "Laughing Skull (US)"),
         ("Lethon (US)" , "Lethon (US)"),
         ("Lightbringer (US)" , "Lightbringer (US)"),
         ("Lightning's Blade (US)" , "Lightning's Blade (US)"),
         ("Lightninghoof (US)" , "Lightninghoof (US)"),
         ("Llane (US)" , "Llane (US)"),
         ("Lothar (US)" , "Lothar (US)"),
         ("Madoran (US)" , "Madoran (US)"),
         ("Maelstrom (US)" , "Maelstrom (US)"),
         ("Magtheridon (US)" , "Magtheridon (US)"),
         ("Maiev (US)" , "Maiev (US)"),
         ("Mal'Ganis (US)" , "Mal'Ganis (US)"),
         ("Malfurion (US)" , "Malfurion (US)"),
         ("Malorne (US)" , "Malorne (US)"),
         ("Malygos (US)" , "Malygos (US)"),
         ("Mannoroth (US)" , "Mannoroth (US)"),
         ("Medivh (US)" , "Medivh (US)"),
         ("Misha (US)" , "Misha (US)"),
         ("Mok'Nathal (US)" , "Mok'Nathal (US)"),
         ("Moon Guard (US)" , "Moon Guard (US)"),
         ("Moonrunner (US)" , "Moonrunner (US)"),
         ("Mug'thol (US)" , "Mug'thol (US)"),
         ("Muradin (US)" , "Muradin (US)"),
         ("Nagrand (US)" , "Nagrand (US)"),
         ("Nathrezim (US)" , "Nathrezim (US)"),
         ("Nazgrel (US)" , "Nazgrel (US)"),
         ("Nazjatar (US)" , "Nazjatar (US)"),
         ("Nemesis (US)" , "Nemesis (US)"),
         ("Ner'zhul (US)" , "Ner'zhul (US)"),
         ("Nesingwary (US)" , "Nesingwary (US)"),
         ("Nordrassil (US)" , "Nordrassil (US)"),
         ("Norgannon (US)" , "Norgannon (US)"),
         ("Onyxia (US)" , "Onyxia (US)"),
         ("Perenolde (US)" , "Perenolde (US)"),
         ("Proudmoore (US)" , "Proudmoore (US)"),
         ("Quel'Thalas (US)" , "Quel'Thalas (US)"),
         ("Quel'dorei (US)" , "Quel'dorei (US)"),
         ("Ragnaros (US)" , "Ragnaros (US)"),
         ("Ravencrest (US)" , "Ravencrest (US)"),
         ("Ravenholdt (US)" , "Ravenholdt (US)"),
         ("Rexxar (US)" , "Rexxar (US)"),
         ("Rivendare (US)" , "Rivendare (US)"),
         ("Runetotem (US)" , "Runetotem (US)"),
         ("Sargeras (US)" , "Sargeras (US)"),
         ("Saurfang (US)" , "Saurfang (US)"),
         ("Scarlet Crusade (US)" , "Scarlet Crusade (US)"),
         ("Scilla (US)" , "Scilla (US)"),
         ("Sen'jin (US)" , "Sen'jin (US)"),
         ("Sentinels (US)" , "Sentinels (US)"),
         ("Shadow Council (US)" , "Shadow Council (US)"),
         ("Shadowmoon (US)" , "Shadowmoon (US)"),
         ("Shadowsong (US)" , "Shadowsong (US)"),
         ("Shandris (US)" , "Shandris (US)"),
         ("Shattered Halls (US)" , "Shattered Halls (US)"),
         ("Shattered Hand (US)" , "Shattered Hand (US)"),
         ("Shu'halo (US)" , "Shu'halo (US)"),
         ("Silver Hand (US)" , "Silver Hand (US)"),
         ("Silvermoon (US)" , "Silvermoon (US)"),
         ("Sisters of Elune (US)" , "Sisters of Elune (US)"),
         ("Skullcrusher (US)" , "Skullcrusher (US)"),
         ("Skywall (US)" , "Skywall (US)"),
         ("Smolderthorn (US)" , "Smolderthorn (US)"),
         ("Spinebreaker (US)" , "Spinebreaker (US)"),
         ("Spirestone (US)" , "Spirestone (US)"),
         ("Staghelm (US)" , "Staghelm (US)"),
         ("Steamwheedle Cartel (US)" , "Steamwheedle Cartel (US)"),
         ("Stonemaul (US)" , "Stonemaul (US)"),
         ("Stormrage (US)" , "Stormrage (US)"),
         ("Stormreaver (US)" , "Stormreaver (US)"),
         ("Stormscale (US)" , "Stormscale (US)"),
         ("Suramar (US)" , "Suramar (US)"),
         ("Tanaris (US)" , "Tanaris (US)"),
         ("Terenas (US)" , "Terenas (US)"),
         ("Terokkar (US)" , "Terokkar (US)"),
         ("Thaurissan (US)" , "Thaurissan (US)"),
         ("The Forgotten Coast (US)" , "The Forgotten Coast (US)"),
         ("The Scryers (US)" , "The Scryers (US)"),
         ("The Underbog (US)" , "The Underbog (US)"),
         ("The Venture Co (US)" , "The Venture Co (US)"),
         ("Thorium Brotherhood (US)" , "Thorium Brotherhood (US)"),
         ("Thrall (US)" , "Thrall (US)"),
         ("Thunderhorn (US)" , "Thunderhorn (US)"),
         ("Thunderlord (US)" , "Thunderlord (US)"),
         ("Tichondrius (US)" , "Tichondrius (US)"),
         ("Tol Barad (US)" , "Tol Barad (US)"),
         ("Tortheldrin (US)" , "Tortheldrin (US)"),
         ("Trollbane (US)" , "Trollbane (US)"),
         ("Turalyon (US)" , "Turalyon (US)"),
         ("Twisting Nether (US)" , "Twisting Nether (US)"),
         ("Uldaman (US)" , "Uldaman (US)"),
         ("Uldum (US)" , "Uldum (US)"),
         ("Undermine (US)" , "Undermine (US)"),
         ("Ursin (US)" , "Ursin (US)"),
         ("Uther (US)" , "Uther (US)"),
         ("Vashj (US)" , "Vashj (US)"),
         ("Vek'nilash (US)" , "Vek'nilash (US)"),
         ("Velen (US)" , "Velen (US)"),
         ("Warsong (US)" , "Warsong (US)"),
         ("Whisperwind (US)" , "Whisperwind (US)"),
         ("Wildhammer (US)" , "Wildhammer (US)"),
         ("Windrunner (US)" , "Windrunner (US)"),
         ("Winterhoof (US)" , "Winterhoof (US)"),
         ("Wyrmrest Accord (US)" , "Wyrmrest Accord (US)"),
         ("Ysera (US)" , "Ysera (US)"),
         ("Ysondre (US)" , "Ysondre (US)"),
         ("Zangarmarsh (US)" , "Zangarmarsh (US)"),
         ("Zul'jin (US)" , "Zul'jin (US)"),
         ("Zuluhed (US)" , "Zuluhed (US)")], default='Web Site')

class char_form(Form):
    charname = StringField('Character Name', [validators.Length(min=4, max=30)])
